services:
  - type: web
    name: APIWebsite
    env: java
    region: oregon
    buildCommand: "./mvnw clean package"  # Use ./gradlew build if using Gradle
    startCommand: "java -jar out/artifacts/mosi_jar/mosi.jar"
    plan: free
